from django.db import models

# Create your models here.


class Juncao(models.Model):
    vsatname = models.CharField(max_length=8)
    nmd = models.CharField(max_length=200)
    ender = models.CharField(max_length=200)
    municipio = models.CharField(max_length=200)
    UF = models.CharField(max_length=200)
    junserviço = models.CharField(max_length=200)
    compart = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    nomeserv = models.CharField(max_length=200)
    fone = models.CharField(max_length=200)
    primeid = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    serial = models.CharField(max_length=200)
    softprof = models.CharField(max_length=200)
    devicetype = models.CharField(max_length=200)
    ipmgmt = models.CharField(max_length=200)
    iplan1 = models.CharField(max_length=200)
    mask = models.CharField(max_length=200)
    servplan = models.CharField(max_length=200)
    AIS = models.CharField(max_length=200)
    OutrouteGroup = models.CharField(max_length=200)
    FAP = models.CharField(max_length=200)
    IPGW = models.CharField(max_length=200)
    Ipipgw = models.CharField(max_length=200)
    IQoS = models.CharField(max_length=200)
    IQoSnum = models.CharField(max_length=200)
    Enable = models.CharField(max_length=200)
    vadb = models.CharField(max_length=200)
    vadb1 = models.CharField(max_length=200)
    vadb2 = models.CharField(max_length=200)
    Enable = models.CharField(max_length=200)
    DDR = models.CharField(max_length=200)


class BDN(models.Model):
    jc_agen = models.CharField(max_length=8)
    jc_BDN = models.CharField(max_length=9)
    nome_BDN = models.CharField(max_length=200)
    UF = models.CharField(max_length=200)
    meio_titular = models.CharField(max_length=200)
    backup = models.CharField(max_length=200)
    id_num = models.CharField(max_length=200)
    ip_BDN = models.CharField(max_length=200)
    masc_BDN = models.CharField(max_length=200)
    gateway_BDN = models.CharField(max_length=200)
    loop_back = models.CharField(max_length=200)
    VMAC = models.CharField(max_length=200)
    ip_vlan_internet = models.CharField(max_length=200)
    categoria_bradesco = models.CharField(max_length=200)
    juncao = models.CharField(max_length=200)
    vsat = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    serial = models.CharField(max_length=200)
    IP = models.CharField(max_length=200)
    DNCC = models.CharField(max_length=200)
    IPGW = models.CharField(max_length=200)
    HUB = models.CharField(max_length=200)
    LoadBalance = models.CharField(max_length=200)
    categori = models.CharField(max_length=200)
    vsat = models.CharField(max_length=200)
    serial = models.CharField(max_length=200)
    IP = models.CharField(max_length=200)
